# Generated by Django 5.2.8 on 2026-02-22 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='moodentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mood_entries', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', '-created_at'], name='main_journa_user_id_78cd96_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', '-created_at'], name='main_mooden_user_id_67fb82_idx'),
        ),
    ]
