# Generated by Django 5.2.8 on 2026-02-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seed_mood_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
