# Generated by Django 5.2.8 on 2026-02-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_moodentry_mood_alter_moodentry_stress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
